#!/bin/bash

# Dossier source et destination

SOURCE_DIR="/home/noe/cibig_noe/project_stage_tutore/raw_data/Metagenomics/sugarecane_demux"
Dest_dir="/home/noe/cibig_noe/project_stage_tutore/raw_data"

# Créer le dossier de destination s'il n'existe pas
mkdir -p "$Dest_dir"

# Boucle sur les barcodes (75 à 85)
for b in {75..85}; do
    # Créer le dossier spécifique pour le barcode (ex: barcode75)
    TARGET_DIR="$Dest_dir/barcode${b}"
    mkdir -p "$TARGET_DIR"

    echo "Traitement du barcode ${b}..."
# Trouvons tous les fichiers fastq des barcodes dans le dossier source puis copions ses fichiers dans 
    # dans le dossier de destination dans les barcodes correspondantes
    find "$SOURCE_DIR" -type f -name "*barcode${b}*.fastq" | while read -r file; do
        # On extrait le nom du run (ex: AQN321)
      
        BASE_NAME=$(basename "$file")

        # Copie et renommage du fichier 
        cp "$file" "$TARGET_DIR/${BASE_NAME}"
    done
done
